package bl4ckscor3.mod.woolplates;

import java.util.Arrays;

import bl4ckscor3.mod.woolplates.block.BlockWoolPlate;
import net.minecraft.block.Block;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.GameRegistry.ObjectHolder;

@Mod(modid=WoolPlates.MODID, name=WoolPlates.NAME, version=WoolPlates.VERSION, acceptedMinecraftVersions=WoolPlates.MC_VERSION)
@EventBusSubscriber
public class WoolPlates
{
	public static final String MODID = "woolplates";
	public static final String NAME = "Wool Pressure Plates";
	public static final String VERSION = "v1.1";
	public static final String MC_VERSION = "1.12";
	public static final String PREFIX = MODID + ":";

	@ObjectHolder(PREFIX + "wool_plate_white")
	public static final Block WHITE = null;
	@ObjectHolder(PREFIX + "wool_plate_orange")
	public static final Block ORANGE = null;
	@ObjectHolder(PREFIX + "wool_plate_magenta")
	public static final Block MAGENTA = null;
	@ObjectHolder(PREFIX + "wool_plate_light_blue")
	public static final Block LIGHT_BLUE = null;
	@ObjectHolder(PREFIX + "wool_plate_yellow")
	public static final Block YELLOW = null;
	@ObjectHolder(PREFIX + "wool_plate_lime")
	public static final Block LIME = null;
	@ObjectHolder(PREFIX + "wool_plate_pink")
	public static final Block PINK = null;
	@ObjectHolder(PREFIX + "wool_plate_gray")
	public static final Block GRAY = null;
	@ObjectHolder(PREFIX + "wool_plate_silver")
	public static final Block SILVER = null;
	@ObjectHolder(PREFIX + "wool_plate_cyan")
	public static final Block CYAN = null;
	@ObjectHolder(PREFIX + "wool_plate_purple")
	public static final Block PURPLE = null;
	@ObjectHolder(PREFIX + "wool_plate_blue")
	public static final Block BLUE = null;
	@ObjectHolder(PREFIX + "wool_plate_brown")
	public static final Block BROWN = null;
	@ObjectHolder(PREFIX + "wool_plate_green")
	public static final Block GREEN = null;
	@ObjectHolder(PREFIX + "wool_plate_red")
	public static final Block RED = null;
	@ObjectHolder(PREFIX + "wool_plate_black")
	public static final Block BLACK = null;

	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		ModMetadata modMeta = event.getModMetadata();

		modMeta.authorList = Arrays.asList(new String[] {
				"bl4ckscor3"
		});
		modMeta.autogenerated = false;
		modMeta.description = "Adds pressure plates made out of wool.";
	}

	@SubscribeEvent
	public static void registerBlocks(RegistryEvent.Register<Block> event)
	{
		event.getRegistry().register(new BlockWoolPlate("wool_plate_white"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_orange"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_magenta"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_light_blue"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_yellow"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_lime"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_pink"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_gray"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_silver"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_cyan"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_purple"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_blue"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_brown"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_green"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_red"));
		event.getRegistry().register(new BlockWoolPlate("wool_plate_black"));
	}

	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event)
	{
		event.getRegistry().register(new ItemBlock(WHITE).setRegistryName(WHITE.getRegistryName()));
		event.getRegistry().register(new ItemBlock(ORANGE).setRegistryName(ORANGE.getRegistryName()));
		event.getRegistry().register(new ItemBlock(MAGENTA).setRegistryName(MAGENTA.getRegistryName()));
		event.getRegistry().register(new ItemBlock(LIGHT_BLUE).setRegistryName(LIGHT_BLUE.getRegistryName()));
		event.getRegistry().register(new ItemBlock(YELLOW).setRegistryName(YELLOW.getRegistryName()));
		event.getRegistry().register(new ItemBlock(LIME).setRegistryName(LIME.getRegistryName()));
		event.getRegistry().register(new ItemBlock(PINK).setRegistryName(PINK.getRegistryName()));
		event.getRegistry().register(new ItemBlock(GRAY).setRegistryName(GRAY.getRegistryName()));
		event.getRegistry().register(new ItemBlock(SILVER).setRegistryName(SILVER.getRegistryName()));
		event.getRegistry().register(new ItemBlock(CYAN).setRegistryName(CYAN.getRegistryName()));
		event.getRegistry().register(new ItemBlock(PURPLE).setRegistryName(PURPLE.getRegistryName()));
		event.getRegistry().register(new ItemBlock(BLUE).setRegistryName(BLUE.getRegistryName()));
		event.getRegistry().register(new ItemBlock(BROWN).setRegistryName(BROWN.getRegistryName()));
		event.getRegistry().register(new ItemBlock(GREEN).setRegistryName(GREEN.getRegistryName()));
		event.getRegistry().register(new ItemBlock(RED).setRegistryName(RED.getRegistryName()));
		event.getRegistry().register(new ItemBlock(BLACK).setRegistryName(BLACK.getRegistryName()));
	}

	@SubscribeEvent
	public static void registerModels(ModelRegistryEvent event)
	{
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(WHITE), 0, new ModelResourceLocation(PREFIX + "wool_plate_white", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(ORANGE), 0, new ModelResourceLocation(PREFIX + "wool_plate_orange", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(MAGENTA), 0, new ModelResourceLocation(PREFIX + "wool_plate_magenta", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(LIGHT_BLUE), 0, new ModelResourceLocation(PREFIX + "wool_plate_light_blue", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(YELLOW), 0, new ModelResourceLocation(PREFIX + "wool_plate_yellow", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(LIME), 0, new ModelResourceLocation(PREFIX + "wool_plate_lime", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(PINK), 0, new ModelResourceLocation(PREFIX + "wool_plate_pink", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(GRAY), 0, new ModelResourceLocation(PREFIX + "wool_plate_gray", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(SILVER), 0, new ModelResourceLocation(PREFIX + "wool_plate_silver", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(CYAN), 0, new ModelResourceLocation(PREFIX + "wool_plate_cyan", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(PURPLE), 0, new ModelResourceLocation(PREFIX + "wool_plate_purple", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(BLUE), 0, new ModelResourceLocation(PREFIX + "wool_plate_blue", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(BROWN), 0, new ModelResourceLocation(PREFIX + "wool_plate_brown", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(GREEN), 0, new ModelResourceLocation(PREFIX + "wool_plate_green", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(RED), 0, new ModelResourceLocation(PREFIX + "wool_plate_red", "inventory"));
		ModelLoader.setCustomModelResourceLocation(Item.getItemFromBlock(BLACK), 0, new ModelResourceLocation(PREFIX + "wool_plate_black", "inventory"));
	}
}
