modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/WoolPlates/blob/1.21.3/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/WoolPlates/issues"

[[mods]]
	modId="woolplates"
	version="${file.jarVersion}"
	displayName="Wool Pressure Plates"
	description='''Adds pressure plates made out of wool.'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wool-pressure-plates"
	authors="bl4ckscor3"

[[dependencies.woolplates]]
    modId="neoforge"
    type="required"
    versionRange="[21.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woolplates]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.3,1.22)"
    ordering="NONE"
    side="BOTH"